name: algorand_dart
description: Unofficial community SDK to interact with the Algorand network, for Dart & Flutter
version: 2.0.0-dev.14
homepage: https://www.algorand.com
repository: https://github.com/RootSoft/algorand-dart
issue_tracker: https://github.com/RootSoft/algorand-dart/issues

environment:
  sdk: ^3.8.0

dependencies:
  # Ed25519
  cryptography:

  # SHA512/256
  crypto:

  # Base32
  base32:

  # Convert
  convert:

  # Easily work with bytes
  buffer:

  # Equatable
  equatable:

  # JSON Annotation
  json_annotation:

  # Equality
  collection:

  # HTTP & REST
  dio:
  retrofit:

  # Messagepack
  algorand_msgpack:

  #algorand_json:
  jsontool:

dev_dependencies:
  # Testing framework
  test:

  flutter_lints:

  # Build Runner & Source Generation
  build_runner:

  # Linter
  lints:

  # JSON Serialization
  json_serializable:

  # Retrofit
  retrofit_generator: